{"name": "Ошибка при получении заказа неавторизованным пользователем", "status": "passed", "start": 1718962733285, "stop": 1718962734239, "uuid": "05623dd1-51d5-46a9-9337-fa9a50ecd7f9", "historyId": "5baaf3849fcbd18ae3901d4f3f63afcf", "testCaseId": "5baaf3849fcbd18ae3901d4f3f63afcf", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_user_without_authorisation_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-G789T9B"}, {"name": "thread", "value": "11396-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}