{"name": "Ошибка при получении заказа неавторизованным пользователем", "status": "passed", "start": 1718826689995, "stop": 1718826690837, "uuid": "9d8fde75-8a45-4959-a40c-5a5ea9e59bbd", "historyId": "5baaf3849fcbd18ae3901d4f3f63afcf", "testCaseId": "5baaf3849fcbd18ae3901d4f3f63afcf", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_user_without_authorisation_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-G789T9B"}, {"name": "thread", "value": "17000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}